-- MySQL Script generated by MySQL Workbench
-- Thu Jun  4 10:59:10 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`продукция`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`продукция` (
  `id_продукты` INT NULL AUTO_INCREMENT,
  `название` VARCHAR(100) NOT NULL,
  `цена` DECIMAL(10,2) NOT NULL,
  `ед_изм` VARCHAR(10) NULL,
  PRIMARY KEY (`id_продукты`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`материалы`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`материалы` (
  `id_материалы` INT NULL AUTO_INCREMENT,
  `названия` VARCHAR(100) NOT NULL,
  `цена` DECIMAL(10,2) NOT NULL,
  `ед_изм` VARCHAR(10) NULL,
  PRIMARY KEY (`id_материалы`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`состав_продукции`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`состав_продукции` (
  `id_продукции` INT NULL,
  `id_материала` INT NULL,
  `норма_расхода` DECIMAL(10,3) NOT NULL,
  PRIMARY KEY (`id_продукции`, `id_материала`),
  CONSTRAINT `продукция`
    FOREIGN KEY (`id_продукции`)
    REFERENCES `mydb`.`продукция` (`id_продукты`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`заказчики`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`заказчики` (
  `id_заказчика` INT NULL AUTO_INCREMENT,
  `название` VARCHAR(100) NOT NULL,
  `контактное_лицо` VARCHAR(100) NULL,
  `телефон` VARCHAR(20) NULL,
  `email` VARCHAR(100) NULL,
  PRIMARY KEY (`id_заказчика`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`заказы`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`заказы` (
  `id_заказа` INT NULL AUTO_INCREMENT,
  `дата` DATE NOT NULL,
  `id_заказчика` INT NULL,
  PRIMARY KEY (`id_заказа`),
  INDEX `заказчики_idx` (`id_заказчика` ASC) VISIBLE,
  CONSTRAINT `заказчики`
    FOREIGN KEY (`id_заказчика`)
    REFERENCES `mydb`.`заказчики` (`id_заказчика`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`состав_заказа`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`состав_заказа` (
  `id_заказа` INT NULL,
  `id_продукции` INT NULL,
  `количество` INT NULL,
  `состав_заказаcol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_заказа`, `id_продукции`),
  CONSTRAINT `заказы`
    FOREIGN KEY ()
    REFERENCES `mydb`.`заказы` ()
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `продукция`
    FOREIGN KEY (`id_заказа`)
    REFERENCES `mydb`.`продукция` (`id_продукты`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
